name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/project-action@release
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install package
        run: make install
      - name: Run linter
        run: make lint
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
